stages:
  - test
  - build
  - build-docker

test_demo:
  stage: test
  image: node:16.13.1-alpine
  script:
    - echo "testing testing"

test_vuejs:
  stage: test
  image: node:16.13.1-alpine
  script:
    - cd frontend
    - npm install 
    - npm run test

build_django:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/django-react3_backend:1 ./backend
    - docker push gerrome/django-react3_backend:1

build_react-nginx:
  stage: build-docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t gerrome/django-react3_nginx:1 ./frontend
    - docker push gerrome/django-react3_nginx:1


